apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
data:
  DB_URL: jdbc:postgresql://host.docker.internal:5433/bank_db
  DB_USERNAME: henriquelobo
  HTTP_PORT: "8082"
  GRPC_PORT: "9090"
  JWT_EXPIRATION: "3600"
